name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["type: bug", "status: needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 
        This helps us improve this project for everyone.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: When I use this feature..., I expected..., but instead...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide step-by-step instructions to reproduce the issue
      placeholder: |
        1. Run the command or use the feature...
        2. Observe the output...
        3. Expected: ...
        4. Actual: ...
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: The application should...
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What actually happened? Include any error messages.
      placeholder: |
        The application outputs:
        ```
        Error: ...
        ```
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of this project are you using?
      placeholder: "v1.0.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Other (please specify in additional context)
    validations:
      required: true

  - type: input
    id: os_version
    attributes:
      label: OS Version
      description: Specific OS version (e.g., Ubuntu 22.04, macOS 13.0, Windows 11)
      placeholder: "Ubuntu 22.04"

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here.
        - Are you using any special configuration?
        - Does this happen with specific inputs?
        - Any workarounds you've found?

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid creating duplicates
          required: true
        - label: I have provided all the requested information above
          required: true
        - label: I can reproduce this issue consistently
          required: true