name: ❓ Question
description: Ask a question about usage or functionality
title: "[Question]: "
labels: ["type: question", "status: needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your question! This template helps organize and track questions about the project.

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know about this project?
      placeholder: How do I compare JSON files while ignoring certain keys?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: |
        Provide any relevant context or background information that would help us answer your question.
        What are you trying to accomplish?
      placeholder: |
        I'm working on a CI/CD pipeline where I need to compare configuration files but ignore timestamps.
        I've tried... but I'm not sure how to...

  - type: textarea
    id: attempted_solutions
    attributes:
      label: What You've Tried
      description: |
        What have you already tried? Include any documentation you've checked.
      placeholder: |
        I've checked:
        - The README.md file
        - The documentation in docs/user-guide/
        - Searched existing issues
        
        I've tried:
        - command --option value
        - Looking at the --help output

  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      description: How urgent is this question for you?
      options:
        - Low - Just curious
        - Medium - Would help my current work
        - High - Blocking my current task
    validations:
      required: true

  - type: textarea
    id: version_info
    attributes:
      label: Environment (Optional)
      description: |
        If relevant to your question, provide version information
      placeholder: |
        version: 1.0.0
        OS: Ubuntu 22.04
        Use case: CI/CD configuration validation

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm you've done the following
      options:
        - label: I have searched existing issues and discussions for similar questions
          required: true
        - label: I have provided enough context for others to understand my question
          required: true