name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:
    inputs:
      project-name:
        description: 'Project name (e.g., diffx, lawkit, diffai)'
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Run CI tests
      run: |
        chmod +x ./mnt/rust-cli-kiln/scripts/testing/quick-check.sh
        ./mnt/rust-cli-kiln/scripts/testing/quick-check.sh
