name: Rust CLI Kiln - CI Build and Test

on:
  workflow_call:
    inputs:
      project-name:
        description: 'Project name (diffx, diffai, or lawkit)'
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: ${{ format('kako-jun/{0}', inputs.project-name) }}
        ref: ${{ github.ref }}
      
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
      
    - name: Add uv to PATH
      run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        
    - name: Cache Rust dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
          
    - name: Checkout .github repository
      uses: actions/checkout@v4
      with:
        repository: kako-jun/.github
        path: .github
        
    - name: Create github-shared symlink
      run: |
        # Create the symlink using the provided script
        chmod +x scripts/utils/create-github-shared-symlink.sh
        ./scripts/utils/create-github-shared-symlink.sh
        
    - name: Setup environment and run build-and-test
      run: |
        # Setup environment variables for workflow type
        export WORKFLOW_CALL_PROJECT="${{ inputs.project-name }}"
        
        # Source common.sh from the symlinked .github
        source github-shared/rust-cli-kiln/scripts/utils/common.sh
        
        setup_github_actions_env
        
        github-shared/rust-cli-kiln/scripts/release/05-build-and-test.sh