name: Rust CLI Kiln - CI Build and Test

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - '*.md'
      - 'docs/**'
      - '.github/**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '*.md'
      - 'docs/**'
      - '.github/**.md'
  workflow_dispatch:
    inputs:
      project-name:
        description: 'Project to run CI for'
        required: true
        type: choice
        options:
        - diffx
        - diffai
        - lawkit
  workflow_call:
    inputs:
      project-name:
        description: 'Project name (diffx, diffai, or lawkit)'
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Debug event info
      run: |
        echo "Event name: ${{ github.event_name }}"
        echo "Input project-name (inputs): ${{ inputs.project-name }}"
        echo "Input project-name (event.inputs): ${{ github.event.inputs.project-name }}"
        echo "Repository: ${{ github.repository }}"
        
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event_name == 'workflow_call' && format('kako-jun/{0}', inputs.project-name) || github.event_name == 'workflow_dispatch' && format('kako-jun/{0}', github.event.inputs.project-name) || github.repository }}
        ref: ${{ github.event_name == 'workflow_dispatch' && 'main' || github.ref }}
        
    - name: Setup rust-cli-kiln symlink (for workflow_call or workflow_dispatch)
      if: github.event_name == 'workflow_call' || github.event_name == 'workflow_dispatch'
      run: |
        # Clone the .github repository to get rust-cli-kiln scripts
        git clone https://github.com/kako-jun/.github.git /tmp/github-repo
        
        # Create symlink to rust-cli-kiln
        mkdir -p .github
        ln -s /tmp/github-repo/rust-cli-kiln .github/rust-cli-kiln
        
        # Verify current directory and contents
        echo "Current directory: $(pwd)"
        echo "Contents:"
        ls -la
        echo "Cargo.toml check:"
        cat Cargo.toml | head -5 || echo "No Cargo.toml found"
      
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
      
    - name: Add uv to PATH
      run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        
    - name: Cache Rust dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
          
    - name: Detect project and run build-and-test
      run: |
        # Determine project and navigate to correct directory
        if [ "${{ github.event_name }}" = "workflow_call" ]; then
          # For workflow_call, we're already in the project directory
          PROJECT_NAME="${{ inputs.project-name }}"
          echo "Using project from workflow_call: $PROJECT_NAME"
        elif [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          # For workflow_dispatch, we're already in the project directory
          PROJECT_NAME="${{ github.event.inputs.project-name }}"
          echo "Using project from workflow_dispatch: $PROJECT_NAME"
          
          if [ ! -f "Cargo.toml" ]; then
            echo "Error: Not in project directory (workflow_call/workflow_dispatch)"
            pwd
            ls -la
            exit 1
          fi
        else
          # Auto-detect from directory structure
          for project in diffx diffai lawkit; do
            if [ -d "../$project" ] && [ -f "../$project/Cargo.toml" ]; then
              PROJECT_NAME="$project"
              echo "Found project: $PROJECT_NAME"
              cd "../$PROJECT_NAME"
              break
            fi
          done
          
          if [ ! -f "Cargo.toml" ]; then
            echo "Error: No project with Cargo.toml found"
            echo "Available directories:"
            ls -la ../
            exit 1
          fi
        fi
        
        echo "Running build and test for $PROJECT_NAME..."
        ./.github/rust-cli-kiln/scripts/release/05-build-and-test.sh