name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:
    inputs:
      project-name:
        description: 'Project name (e.g., diffx, lawkit, diffai)'
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout shared repository
      uses: actions/checkout@v4
      with:
        repository: kako-jun/.github
        path: .github-shared
        
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Debug and run CI tests
      run: |
        echo "=== Debug: Current directory ==="
        pwd
        echo "=== Debug: List files ==="
        ls -la
        echo "=== Debug: Check .github-shared ==="
        ls -la .github-shared/
        echo "=== Debug: Check rust-cli-kiln ==="
        ls -la .github-shared/rust-cli-kiln/
        echo "=== Debug: Check scripts ==="
        ls -la .github-shared/rust-cli-kiln/scripts/
        echo "=== Debug: Check utils ==="
        ls -la .github-shared/rust-cli-kiln/scripts/utils/
        echo "=== Debug: Check common.sh ==="
        cat .github-shared/rust-cli-kiln/scripts/utils/common.sh | head -10
        echo "=== Debug: Check quick-check.sh ==="
        cat .github-shared/rust-cli-kiln/scripts/testing/quick-check.sh | head -15
        echo "=== Debug: Run script ==="
        chmod +x ./.github-shared/rust-cli-kiln/scripts/testing/quick-check.sh
        ./.github-shared/rust-cli-kiln/scripts/testing/quick-check.sh
