name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:
    inputs:
      project-name:
        description: 'Project name (e.g., diffx, lawkit, diffai)'
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout project repository
      uses: actions/checkout@v4
      
    - name: Debug repository access
      run: |
        echo "Testing repository access..."
        curl -s "https://api.github.com/repos/kako-jun/.github" | jq '.private' || echo "Repository access failed"
        
    - name: Checkout shared repository
      uses: actions/checkout@v3
      with:
        repository: kako-jun/.github
        path: github-shared
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Verify shared repository structure
      run: |
        echo "=== Verifying shared repository structure ==="
        ls -la github-shared/
        ls -la github-shared/rust-cli-kiln/
        ls -la github-shared/rust-cli-kiln/scripts/
        
    - name: Run CI tests
      run: |
        chmod +x ./github-shared/rust-cli-kiln/scripts/testing/quick-check.sh
        ./github-shared/rust-cli-kiln/scripts/testing/quick-check.sh
