name: Rust CLI Kiln - Release Build and Publish

on:
  workflow_call:
    inputs:
      project-name:
        description: 'Project name (diffx, diffai, or lawkit)'
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: ${{ format('kako-jun/{0}', inputs.project-name) }}
        ref: ${{ github.ref }}
        
      
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
      
    - name: Add uv to PATH
      run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        
    - name: Cache Rust dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
          !target/wheels/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
          
    - name: Setup Python environment for maturin
      run: |
        # Install uv and Python dependencies required for Python package building
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        
    - name: Checkout .github repository
      uses: actions/checkout@v4
      with:
        repository: kako-jun/.github
        path: .github
        
    - name: Build Python wheel with manylinux
      uses: messense/maturin-action@v1
      with:
        working-directory: ${{ inputs.project-name }}-python
        manylinux: 2_28
        args: --release --out dist
        
    - name: Setup environment and run build-test-publish sequence
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        # Setup environment variables for workflow type
        export WORKFLOW_CALL_PROJECT="${{ inputs.project-name }}"
        
        # Create symlink and verify it works
        ./scripts/utils/create-github-shared-symlink.sh
        
        # Source common.sh from the symlinked .github
        source github-shared/rust-cli-kiln/scripts/utils/common.sh
        
        # Setup unified environment
        setup_github_actions_env
        
        # Setup Python virtual environment for maturin
        source .venv/bin/activate 2>/dev/null || { uv venv && source .venv/bin/activate; }
        uv pip install maturin wheel build twine
        
        echo "Step 1: Running comprehensive build and test (skip Python wheel build)..."
        export SKIP_PYTHON_WHEEL_BUILD=1
        github-shared/rust-cli-kiln/scripts/release/05-build-and-test.sh && \
        echo "Step 2: Running atomic publish (same environment)..." && \
        github-shared/rust-cli-kiln/scripts/release/06-publish.sh
  
  test-published-packages:
    needs: build-and-publish
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Wait for package propagation
      run: |
        echo "Waiting 60 seconds for packages to propagate across registries..."
        sleep 60
        
    - name: Detect project and test published packages
      run: |
        # This script needs to be run from the actual project directory
        # Find the project directory (contains Cargo.toml with workspace)
        for project in diffx diffai lawkit; do
          if [ -d "../$project" ] && [ -f "../$project/Cargo.toml" ]; then
            echo "Found project: $project"
            cd "../$project"
            echo "Testing published packages for $project..."
            ./.github/rust-cli-kiln/scripts/release/09-test-published-packages.sh
            break
          fi
        done
        
        if [ ! -f "Cargo.toml" ]; then
          echo "Error: No project with Cargo.toml found"
          echo "Available directories:"
          ls -la ../
          exit 1
        fi