name: Performance Benchmark

on:
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_call:
    inputs:
      project-name:
        description: 'Project name (e.g., diffx, lawkit, diffai)'
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmark:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout project repository
      uses: actions/checkout@v4
      
    - name: Checkout shared repository
      uses: actions/checkout@v4
      with:
        repository: kako-jun/.github
        path: github-shared
        
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-bench-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Run benchmarks
      run: |
        # Initialize project variables
        chmod +x ./github-shared/rust-cli-kiln/scripts/utils/common.sh
        source ./github-shared/rust-cli-kiln/scripts/utils/common.sh
        init_project_vars
        
        # Quick benchmark run with minimal sampling
        CARGO_CRITERION_ARGS="--sample-size 5 --measurement-time 0.5" cargo bench --package ${PROJECT_NAME}-core > benchmark_results.txt 2>&1 || true
        
        echo "=== Benchmark Results ==="
        cat benchmark_results.txt
        echo "=========================="
        
        echo "✅ Benchmark completed successfully!"
        
    - name: Upload benchmark results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: benchmark_results.txt
        retention-days: 7